[workspace]
members = [
  "xn-core",
]
exclude = ["xn-flash-attn"]
resolver = "3"

[workspace.package]
version = "0.2.5"
description = "Another minimalist deep-learning framework optimized for inference."
repository = "https://github.com/LaurentMazare/xn"
keywords = ["pytorch", "deep-learning", "machine-learning"]
categories = ["science"]
license = "MIT/Apache-2.0"

[workspace.dependencies]
xn = { path = "xn-core", version = "0.2.5" }
anyhow = "1"
ash = "0.38"
bindgen_cuda = "0.1.6"
byteorder = "1"
clap = { version = "4", features = ["derive"] }
cudarc = { version = "0.19.9", features = ["std", "cublas", "cublaslt", "curand", "driver", "nvrtc", "f16", "cuda-version-from-build-system", "dynamic-linking"] }
gemm = { git = "https://github.com/gradium-ai/gemm", tag = "v0.20.0", version = "0.20.0", features = ["wasm-simd128-enable"] }
half = { version = "2.7.1", features = ["num-traits"] }
hf-hub = { version = "0.5", default-features = false, features = ["ureq"] }
kaudio = "0.2.1"
libc = "0.2"
libm = "0.2"
memmap2 = "0.9"
metal = "0.33"
num-traits = "0.2.19"
num_cpus = "1.17.0"
paste = "1"
pollster = "0.4"
rand = { version = "0.9.0", default-features = false }
rand_distr = "0.5.0"
rayon = "1.11.0"
safetensors = "0.7"
serde_json = "1"
thiserror = "2.0.17"
tokenizers = "0.21"
tracing = "0.1.44"
tracing-chrome = "0.7.2"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
wgpu = "26"
yoke = { version = "0.8.1", features = ["derive"] }

[profile.release]
debug = true

[profile.release-no-debug]
inherits = "release"
debug = false
