fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    #[cfg(feature = "accelerate")]
    {
        println!("cargo:rustc-link-lib=framework=Accelerate");
    }
    #[cfg(feature = "cuda")]
    {
        println!("cargo:rerun-if-changed=src/compatibility.cuh");

        let builder = bindgen_cuda::Builder::default()
            .kernel_paths_glob("cuda-kernels/**/*.cu")
            .arg("--extended-lambda");
        println!("cargo:info={builder:?}");
        let bindings = builder.build_ptx().unwrap();
        bindings.write("src/cuda_backend/kernels.rs").unwrap();
    }
    #[cfg(feature = "vulkan")]
    build_vulkan_shaders();
}

/// Compile every `vulkan-kernels/*.comp` GLSL compute shader to SPIR-V using
/// `glslc` (from the Vulkan SDK / shaderc) and emit a generated module,
/// `$OUT_DIR/vulkan_shaders.rs`, exposing each shader as a `&[u32]` constant
/// named after the file (upper-cased, e.g. `arithmetic.comp` -> `ARITHMETIC`).
#[cfg(feature = "vulkan")]
fn build_vulkan_shaders() {
    use std::io::Write;
    use std::path::Path;

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let shader_dir = Path::new("vulkan-kernels");
    println!("cargo:rerun-if-changed=vulkan-kernels");

    let mut entries: Vec<_> = std::fs::read_dir(shader_dir)
        .expect("failed to read vulkan-kernels directory")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("comp"))
        .collect();
    entries.sort();

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs - do not edit\n");
    // Each shader is compiled twice: an f32 variant and an `-DUSE_F16` variant
    // (float16_t storage). The f16 variant needs a newer target-env for the
    // 16-bit-storage / float16 extensions.
    // 16-bit variants need vulkan1.1 (SPIR-V 1.3) for the 16-bit storage and
    // arithmetic-type capabilities; this matches the apiVersion the backend
    // declares at instance creation.
    let variants = [
        ("F32", "vulkan1.0", None),
        ("F16", "vulkan1.1", Some("USE_F16")),
        ("BF16", "vulkan1.1", Some("USE_BF16")),
    ];
    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path.file_stem().and_then(|s| s.to_str()).unwrap();
        if stem == "cast" {
            // cast.comp uses (SRC, DST) define pairs instead of dtype variants.
            continue;
        }
        let base = stem.to_uppercase().replace('-', "_");
        // Pure data-movement kernels also get an i64 (uvec2) variant so that
        // i64 tensors (kv-cache indices, token ids) stay on the GPU path.
        let i64_variant: &[_] = if matches!(
            stem,
            "copy2d" | "copy_strided" | "transpose" | "index_select" | "scatter_set"
        ) {
            &[("I64", "vulkan1.0", Some("USE_I64"))]
        } else {
            &[]
        };
        // The q8_0 weight kernels read f32 activations and packed int8
        // weights whatever the model's compute dtype, so they get one build.
        let f32_only: &[_] = &variants[..1];
        // The subgroup variant needs SPIR-V 1.3 for GroupNonUniform ops.
        let f32_subgroup: &[_] = &[("F32", "vulkan1.1", None)];
        // Row-block kernels are built once per block height MR.
        let row_blocks: &[_] = &[
            ("R1", "vulkan1.1", Some("MR=1")),
            ("R2", "vulkan1.1", Some("MR=2")),
            ("R4", "vulkan1.1", Some("MR=4")),
            ("R8", "vulkan1.1", Some("MR=8")),
            ("R16", "vulkan1.1", Some("MR=16")),
        ];
        let shader_variants: Vec<_> = match stem {
            "gemv_q8" | "gemm_q8" | "dequant_q8" => f32_only.to_vec(),
            "gemv_q8_sg" => f32_subgroup.to_vec(),
            "gemm_q8_sg" => row_blocks.to_vec(),
            _ => variants.iter().chain(i64_variant).copied().collect(),
        };
        for (suffix, target, define) in shader_variants {
            let spv_path = Path::new(&out_dir).join(format!("{stem}_{suffix}.spv"));
            let mut cmd = std::process::Command::new("glslc");
            cmd.arg(format!("--target-env={target}")).arg("-O");
            if let Some(d) = define {
                cmd.arg(format!("-D{d}"));
            }
            let status = cmd
                .arg("-o")
                .arg(&spv_path)
                .arg(path)
                .status()
                .expect("failed to spawn glslc - is the Vulkan SDK / shaderc installed?");
            if !status.success() {
                panic!("glslc failed to compile {} ({suffix})", path.display());
            }
            generated.push_str(&format!(
                "pub static {base}_{suffix}: &[u8] = include_bytes!(r\"{}\");\n",
                spv_path.display()
            ));
        }
    }

    // cast.comp: one compile per supported (src, dst) dtype pair.
    let cast_pairs =
        ["f32_f16", "f16_f32", "f32_bf16", "bf16_f32", "f16_bf16", "bf16_f16", "i64_f32"];
    let cast_src = shader_dir.join("cast.comp");
    for pair in cast_pairs {
        let (src, dst) = pair.split_once('_').unwrap();
        let spv_path = Path::new(&out_dir).join(format!("cast_{pair}.spv"));
        let status = std::process::Command::new("glslc")
            .arg("--target-env=vulkan1.1")
            .arg("-O")
            .arg(format!("-DSRC_{}", src.to_uppercase()))
            .arg(format!("-DDST_{}", dst.to_uppercase()))
            .arg("-o")
            .arg(&spv_path)
            .arg(&cast_src)
            .status()
            .expect("failed to spawn glslc - is the Vulkan SDK / shaderc installed?");
        if !status.success() {
            panic!("glslc failed to compile cast.comp ({pair})");
        }
        generated.push_str(&format!(
            "pub static CAST_{}: &[u8] = include_bytes!(r\"{}\");\n",
            pair.to_uppercase(),
            spv_path.display()
        ));
    }

    let dest = Path::new(&out_dir).join("vulkan_shaders.rs");
    let mut f = std::fs::File::create(&dest).expect("failed to create vulkan_shaders.rs");
    f.write_all(generated.as_bytes()).expect("failed to write vulkan_shaders.rs");
}
