fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    #[cfg(feature = "accelerate")]
    {
        println!("cargo:rustc-link-lib=framework=Accelerate");
    }
    #[cfg(feature = "xnnpack")]
    link_xnnpack();
    #[cfg(feature = "cuda")]
    {
        println!("cargo:rerun-if-changed=src/compatibility.cuh");

        let builder = bindgen_cuda::Builder::default()
            .kernel_paths_glob("cuda-kernels/**/*.cu")
            .arg("--extended-lambda");
        println!("cargo:info={builder:?}");
        let bindings = builder.build_ptx().unwrap();
        bindings.write("src/cuda_backend/kernels.rs").unwrap();
    }
    #[cfg(feature = "vulkan")]
    build_vulkan_shaders();
}

/// Compile every `vulkan-kernels/*.comp` GLSL compute shader to SPIR-V using
/// `glslc` (from the Vulkan SDK / shaderc) and emit a generated module,
/// `$OUT_DIR/vulkan_shaders.rs`, exposing each shader as a `&[u32]` constant
/// named after the file (upper-cased, e.g. `arithmetic.comp` -> `ARITHMETIC`).
#[cfg(feature = "vulkan")]
fn build_vulkan_shaders() {
    use std::io::Write;
    use std::path::Path;

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let shader_dir = Path::new("vulkan-kernels");
    println!("cargo:rerun-if-changed=vulkan-kernels");

    let mut entries: Vec<_> = std::fs::read_dir(shader_dir)
        .expect("failed to read vulkan-kernels directory")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("comp"))
        .collect();
    entries.sort();

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs - do not edit\n");
    // Each shader is compiled twice: an f32 variant and an `-DUSE_F16` variant
    // (float16_t storage). The f16 variant needs a newer target-env for the
    // 16-bit-storage / float16 extensions.
    // 16-bit variants need vulkan1.1 (SPIR-V 1.3) for the 16-bit storage and
    // arithmetic-type capabilities; this matches the apiVersion the backend
    // declares at instance creation.
    let variants = [
        ("F32", "vulkan1.0", None),
        ("F16", "vulkan1.1", Some("USE_F16")),
        ("BF16", "vulkan1.1", Some("USE_BF16")),
    ];
    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path.file_stem().and_then(|s| s.to_str()).unwrap();
        if stem == "cast" {
            // cast.comp uses (SRC, DST) define pairs instead of dtype variants.
            continue;
        }
        let base = stem.to_uppercase().replace('-', "_");
        // Pure data-movement kernels also get an i64 (uvec2) variant so that
        // i64 tensors (kv-cache indices, token ids) stay on the GPU path.
        let i64_variant: &[_] = if matches!(
            stem,
            "copy2d" | "copy_strided" | "transpose" | "index_select" | "scatter_set"
        ) {
            &[("I64", "vulkan1.0", Some("USE_I64"))]
        } else {
            &[]
        };
        for (suffix, target, define) in variants.iter().chain(i64_variant) {
            let spv_path = Path::new(&out_dir).join(format!("{stem}_{suffix}.spv"));
            let mut cmd = std::process::Command::new("glslc");
            cmd.arg(format!("--target-env={target}")).arg("-O");
            if let Some(d) = define {
                cmd.arg(format!("-D{d}"));
            }
            let status = cmd
                .arg("-o")
                .arg(&spv_path)
                .arg(path)
                .status()
                .expect("failed to spawn glslc - is the Vulkan SDK / shaderc installed?");
            if !status.success() {
                panic!("glslc failed to compile {} ({suffix})", path.display());
            }
            generated.push_str(&format!(
                "pub static {base}_{suffix}: &[u8] = include_bytes!(r\"{}\");\n",
                spv_path.display()
            ));
        }
    }

    // cast.comp: one compile per supported (src, dst) dtype pair.
    let cast_pairs =
        ["f32_f16", "f16_f32", "f32_bf16", "bf16_f32", "f16_bf16", "bf16_f16", "i64_f32"];
    let cast_src = shader_dir.join("cast.comp");
    for pair in cast_pairs {
        let (src, dst) = pair.split_once('_').unwrap();
        let spv_path = Path::new(&out_dir).join(format!("cast_{pair}.spv"));
        let status = std::process::Command::new("glslc")
            .arg("--target-env=vulkan1.1")
            .arg("-O")
            .arg(format!("-DSRC_{}", src.to_uppercase()))
            .arg(format!("-DDST_{}", dst.to_uppercase()))
            .arg("-o")
            .arg(&spv_path)
            .arg(&cast_src)
            .status()
            .expect("failed to spawn glslc - is the Vulkan SDK / shaderc installed?");
        if !status.success() {
            panic!("glslc failed to compile cast.comp ({pair})");
        }
        generated.push_str(&format!(
            "pub static CAST_{}: &[u8] = include_bytes!(r\"{}\");\n",
            pair.to_uppercase(),
            spv_path.display()
        ));
    }

    let dest = Path::new(&out_dir).join("vulkan_shaders.rs");
    let mut f = std::fs::File::create(&dest).expect("failed to create vulkan_shaders.rs");
    f.write_all(generated.as_bytes()).expect("failed to write vulkan_shaders.rs");
}

/// Link a prebuilt XNNPACK.
///
/// The tree is located from `XNNPACK_DIR` if set, else a `XNNPACK` sibling of the workspace
/// this crate sits in, which is where the checkout normally lands. Either way it must be a
/// source tree that has already been built:
///
/// ```text
/// git clone --depth 1 https://github.com/google/XNNPACK.git
/// cd XNNPACK
/// cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release \
///   -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DXNNPACK_LIBRARY_TYPE=static \
///   -DXNNPACK_BUILD_TESTS=OFF -DXNNPACK_BUILD_BENCHMARKS=OFF \
///   -DXNNPACK_BUILD_ALL_MICROKERNELS=OFF -DXNNPACK_ENABLE_KLEIDIAI=OFF
/// ninja -C build XNNPACK
/// ```
///
/// Prebuilt rather than built from here on purpose: XNNPACK is a cmake project of its own and
/// compiling it inside a build script would put minutes onto every clean build of this crate.
#[cfg(feature = "xnnpack")]
fn link_xnnpack() {
    println!("cargo:rerun-if-env-changed=XNNPACK_DIR");
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let manifest = std::path::Path::new(&manifest);
    // xn-core/../.. is the directory holding the sibling checkouts.
    let sibling = manifest.parent().and_then(|p| p.parent()).map(|p| p.join("XNNPACK"));
    let candidates: Vec<std::path::PathBuf> = std::env::var("XNNPACK_DIR")
        .ok()
        .map(std::path::PathBuf::from)
        .into_iter()
        .chain(sibling.clone())
        .collect();

    let dir = candidates
        .iter()
        .find(|d| d.join("build").join("libXNNPACK.a").is_file())
        .unwrap_or_else(|| {
            panic!(
                "the `xnnpack` feature needs a built XNNPACK. Looked for build/libXNNPACK.a \
                 under: {}. Set XNNPACK_DIR, or clone and build XNNPACK next to this \
                 workspace -- see link_xnnpack in build.rs for the cmake invocation.",
                candidates
                    .iter()
                    .map(|p| p.display().to_string())
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        });
    println!("cargo:rerun-if-changed={}", dir.join("build/libXNNPACK.a").display());

    let build = dir.join("build");
    for sub in ["", "pthreadpool", "cpuinfo"] {
        println!("cargo:rustc-link-search=native={}", build.join(sub).display());
    }
    // Order matters for static archives: XNNPACK pulls symbols from the microkernel archive.
    for lib in ["XNNPACK", "xnnpack-microkernels-prod", "pthreadpool", "cpuinfo"] {
        println!("cargo:rustc-link-lib=static={lib}");
    }
    // XNNPACK has C++ translation units (guard variables, std::once).
    println!("cargo:rustc-link-lib=dylib=stdc++");
}
